// Connection Type
const SOCKET_IO = "socket.io";
const STANDARD_WEB_SOCKET = "STANDARD_WEB_SOCKET";

// Socket Message Types
const CONNECTION = "connection";
const DISCONNECT = "disconnect";
const CLOSE = "close";
const MESSAGE = "message";

/* Oreka Message Types */

// Client Master
const FETCH_CLIENT_MASTER_META_DATA = "FETCH_CLIENT_MASTER_META_DATA";
const CLIENT_MASTER_META_DATA = "CLIENT_MASTER_META_DATA";
const FETCH_CLIENT_MASTER_DATA = "FETCH_CLIENT_MASTER_DATA";
const CLIENT_MASTER_DATA = "CLIENT_MASTER_DATA";

// Symbol Master
const FETCH_SYMBOL_MASTER_META_DATA = "FETCH_SYMBOL_MASTER_META_DATA";
const SYMBOL_MASTER_META_DATA = "SYMBOL_MASTER_META_DATA";
const FETCH_SYMBOL_MASTER_DATA = "FETCH_SYMBOL_MASTER_DATA";
const SYMBOL_MASTER_DATA = "SYMBOL_MASTER_DATA";

// Script wise poistion
const FETCH_SCRIPT_WISE_POSITOINS_META_DATA = "FETCH_SCRIPT_WISE_POSITOINS_META_DATA";
const SCRIPT_WISE_POSITION_META_DATA = "SCRIPT_WISE_POSITION_META_DATA";
const FETCH_SCRIPT_WISE_POSITIONS = "FETCH_SCRIPT_WISE_POSITIONS";
const SCRIPT_WISE_POSITIONS_DATA = "SCRIPT_WISE_POSITIONS_DATA";
const SCRIPT_WISE_POSITIONS_DATA_UPDATED = "SCRIPT_WISE_POSITIONS_DATA_UPDATED";

// Net Position
const FETCH_NET_POSITION_META_DATA = "FETCH_NET_POSITION_META_DATA";
const NET_POSITION_META_DATA = "NET_POSITION_META_DATA";
const FETCH_NET_POSITIONS = "FETCH_NET_POSITIONS";
const NET_POSITIONS = "NET_POSITIONS";

// Order
const FETCH_ORDER_META_DATA = "FETCH_ORDER_META_DATA";
const ORDER_META_DATA = "ORDER_META_DATA";
const FETCH_ORDER_DATA = "FETCH_ORDER_DATA";
const ORDER_DATA = "ORDER_DATA";

// Tick data
const FETCH_TICK_DATA = "FETCH_TICK_DATA";
const TICK_DATA = "TICK_DATA";

module.exports = {
  SOCKET_IO, STANDARD_WEB_SOCKET, CONNECTION, DISCONNECT, CLOSE, MESSAGE,
  FETCH_SYMBOL_MASTER_META_DATA, SYMBOL_MASTER_META_DATA,
  FETCH_SYMBOL_MASTER_DATA, SYMBOL_MASTER_DATA,
  FETCH_CLIENT_MASTER_META_DATA, CLIENT_MASTER_META_DATA,
  FETCH_CLIENT_MASTER_DATA, CLIENT_MASTER_DATA,
  FETCH_SCRIPT_WISE_POSITOINS_META_DATA, SCRIPT_WISE_POSITION_META_DATA,
  FETCH_SCRIPT_WISE_POSITIONS, SCRIPT_WISE_POSITIONS_DATA, SCRIPT_WISE_POSITIONS_DATA_UPDATED,
  FETCH_NET_POSITION_META_DATA, NET_POSITION_META_DATA,
  FETCH_NET_POSITIONS, NET_POSITIONS,
  FETCH_ORDER_META_DATA, ORDER_META_DATA,
  FETCH_ORDER_DATA, ORDER_DATA,
  FETCH_TICK_DATA, TICK_DATA
};